
import { Button } from "std-widgets.slint";
import { RoundedButton } from "./icon_button/round_button.slint";


export component Topbar {
    Rectangle {
       background: #2E3440;

        HorizontalLayout {
            spacing: 15px;
            width: 300px;
            height: 40px;
            padding: 0px;
            
            RoundedButton{
                text: "System";
            }
            RoundedButton{
                text: "Process";
            }
            RoundedButton{
                text: "Network";
            }
        
        }
    }    
}