export component SystemPage inherits Window {
    
    GridLayout {
        Row {
            
            HorizontalLayout {
                height: 80px;
                
                
                Rectangle {
                    background: yellow;
                    width: 50%;
                    
                    Text{
                        
                        text: "CPU Detail";
                    }
                }
                Rectangle {
                    background: blue;
                    width: 50%;
                    Text{
                        text: "RAM Detail";
                    }
                }
            }
        }
        Row {
            HorizontalLayout {
                
                width: 300px;
                height: 80px;
            
                alignment: center;
                
                Rectangle {
                    background: red;
                    width: 50%;
                    Text{
                        text: "Disk Detail";
                    }
                }
                Rectangle {
                    background: green;
                    width: 50%;
                    Text{
                        text: "System Info";
                    }
                }
            }
        }
    }

    
}