import { Button } from "std-widgets.slint";
export component RefreshButton  {
    
    VerticalLayout {
        Rectangle {
            background: black;
            
            Image {
                source: @image-url("../../static/icon/new_refresh.png");
                width: 25px;
                height: 25px;
                colorize: white;
            }
            Button {
                
            }
        }
    }
}