import { RoundedButton } from "../icon_button/round_button.slint";
export component PidDisplay {
    
    
    in property <int> pid_number : 0;
    in property <string> pid_name: "pid_name";
    in property <int> ram_used: 0;
    in property <int> cpu_used: 0;
    in property <int> disk_wirte: 0;
    in property <int> disk_read: 0;

    HorizontalLayout {
        spacing: 10px;
        width: 100%;
        Text{
            text: {pid_number};
        }
        
        Text {
            text: {pid_name};
        }
        Text {
            text: {ram_used};
        }
        Text {
            text: {cpu_used};
        }
        Text {
            text: {disk_wirte};
        }
        Text {
            text: {disk_read};
        }
        RoundedButton {
            text: "Kill";
            width: 80px;
            height: 30px;
            padding: 5px;
            
        }




    }
}