import { PidDetail} from "../../struct/process.slint";
import { VerticalBox } from "std-widgets.slint";
import { PidDisplay} from "pid.slint";
export component ShowPid {
    in-out property <[PidDetail]> process_list : [
        {
            pid: 1, process_name: "hdd service", 
            cpu_used: 0.3, 
            memory_used: 22, 
            disk_read: 223, 
            disk_write:425
        },
        {
            pid: 2, process_name: "chrome", 
            cpu_used: 2.2, 
            memory_used: 0, 
            disk_read: 0, 
            disk_write: 0
        },
        {
            pid: 3, process_name: "firefox", 
            cpu_used: 3.1, 
            memory_used: 0, 
            disk_read: 0, 
            disk_write: 0
        },
        {
            
            pid: 4, 
            process_name: "disk service", 
            cpu_used: 1.1, 
            memory_used: 0, 
            disk_read: 0, 
            disk_write: 0
        },
        {
            pid: 5, process_name: "network interchange", 
            cpu_used: 0.8, 
            memory_used: 0, 
            disk_read: 0, 
            disk_write: 0
        },
            
    ];

    VerticalBox {
        for data in root.process_list: thing := PidDisplay{
            pid_number: data.pid;
            pid_name: data.process_name;
            ram_used: data.memory_used;
            cpu_used: data.cpu_used;
            disk_wirte: data.disk_write;
            disk_read: data.disk_read;
        }
    }

}