[package]
name = "rusty_sysmon"
version = "0.1.0"
edition = "2024"

[dependencies]
local-ip-address = "0.6.3"
netstat2 = "0.11.1"
num_cpus = "1.16.0"
plotters = "0.3.7"
sysinfo = "0.34.2"
thiserror = "2.0.12"

